# Branches autorisées pour la publication
branches:
  - main

# Plugins utilisés par semantic-release
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"