# Ajout pour "Publish Test Report"
permissions:
  contents: read
  checks: write


name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Récupération du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Détection automatique du type de projet
      - name: Detect project type
        id: detect
        shell: bash
        run: |
          if [ -f "package.json" ]; then
            echo "project_type=angular" >> "$GITHUB_OUTPUT"
          elif [ -f "build.gradle" ]; then
            echo "project_type=spring" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported project"
            exit 1
          fi

      # (Temporaire) Affichage du type détecté
      - name: Display detected project
        run: echo "Detected project = ${{ steps.detect.outputs.project_type }}"

      # Installation de Node.js uniquement pour Angular
      - name: Setup Node.js
        if: steps.detect.outputs.project_type == 'angular'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Installation de Java uniquement pour Spring Boot
      - name: Setup Java
        if: steps.detect.outputs.project_type == 'spring'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # Donner les droits d'exécution au script
      - name: Make test script executable
        run: chmod +x run-tests.sh

      # Exécuter les tests
      - name: Run tests
        run: ./run-tests.sh

      # Publication des rapports
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Unit Tests
          path: test-results/*.xml
          reporter: java-junit